# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/demo" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/icecast-metadata-js"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/icecast-metadata-player"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/icecast-metadata-stats"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/icecast-metadata-recorder"
    schedule:
      interval: "weekly"
